### ISSUE TITLE
[Regressions for Agent] Need to be discussed

### ISSUE THREAD

**Issue by llmhyy** [llmhyy/microbat#172]
hi @lylytran 

We may need to further discuss the following regressions happen for our agent. Some bug are analyzed quite find before April but now our agent report that they cannot be parsed.

- Incorrect non-deterministic program reported:
Closure-82 and Math-100

- cannot find observable fault step:
Time-16

**Comment by lylytran** [comment]
For Math-100: 
the problem lies in the use of Set which element order is different time to time that leads to different step number between executions.
As in the code below, from line 474-477, the list order of problem.getUnboundParameters() is not always the same as at line 457. a set is used in LinearProblem constructor (LinearProblem line 573). Therefore, sometimes 475 & 476 are execute, sometimes not -> step number of prechecks can be different & we consider it as un-deterministic testcase.


`  public void testBoundParameters() throws EstimationException {
      EstimatedParameter[] p = {
        new EstimatedParameter("unbound0", 2, false),
        new EstimatedParameter("unbound1", 2, false),
        new EstimatedParameter("bound",    2, true)
      };
457.      LinearProblem problem = new LinearProblem(new LinearMeasurement[] {
        new LinearMeasurement(new double[] { 1.0, 1.0, 1.0 },
                              new EstimatedParameter[] { p[0], p[1], p[2] },
                              3.0),
        new LinearMeasurement(new double[] { 1.0, -1.0, 1.0 },
                              new EstimatedParameter[] { p[0], p[1], p[2] },
                              1.0),
        new LinearMeasurement(new double[] { 1.0, 3.0, 2.0 },
                              new EstimatedParameter[] { p[0], p[1], p[2] },
                              7.0)
      });

      GaussNewtonEstimator estimator = new GaussNewtonEstimator(100, 1.0e-6, 1.0e-6);
      estimator.estimate(problem);
      assertTrue(estimator.getRMS(problem) < 1.0e-10);
      double[][] covariances = estimator.getCovariances(problem);
      int i0 = 0, i1 = 1;
474.     if (problem.getUnboundParameters()[0].getName().endsWith("1")) {
475.          i0 = 1;
476.          i1 = 0;
477.      }
      assertEquals(11.0 / 24, covariances[i0][i0], 1.0e-10);
      assertEquals(-3.0 / 24, covariances[i0][i1], 1.0e-10);
      assertEquals(-3.0 / 24, covariances[i1][i0], 1.0e-10);
      assertEquals( 3.0 / 24, covariances[i1][i1], 1.0e-10);

      double[] errors = estimator.guessParametersErrors(problem);
      assertEquals(0, errors[i0], 1.0e-10);
      assertEquals(0, errors[i1], 1.0e-10);

  }`
