### ISSUE TITLE
[Determinance Checking] Check Precheck Mode for Nondeterministic program

### ISSUE THREAD

**Issue by llmhyy** [llmhyy/microbat#173]
Closure-82, Math-100

Shall we do it by next Monday (Jun 4)?

**Comment by lylytran** [comment]
For Math-100:
the problem lies in the use of Set which element order is different time to time that leads to different step number between executions.
As in the code below, from line 474-477, the list order of problem.getUnboundParameters() is not always the same as at line 457. a set is used in LinearProblem constructor (LinearProblem line 573). Therefore, sometimes 475 & 476 are execute, sometimes not -> step number of prechecks can be different & we consider it as un-deterministic testcase.
![screen shot 2018-06-04 at 11 37 53 am](https://user-images.githubusercontent.com/7779337/40904668-07f05e58-680e-11e8-853a-fcd44446a0c5.png)

For Closure-82:
method call trace:
com.google.javascript.rhino.jstype.JSTypeRegistry, line=457
com.google.javascript.rhino.jstype.JSTypeRegistry, line=938
com.google.javascript.rhino.jstype.UnionTypeBuilder, line=195
com.google.javascript.rhino.jstype.UnionTypeBuilder, line=212
com.google.javascript.rhino.jstype.UnionTypeBuilder, line=204
Since the comparator for sorting on list based on hashcode(), and one of its element's hashcode is calculated using System.identityHashCode() 
which returns memory address of the object, that makes the trace different.
